services:
  mariadb:
    image: mariadb:11.3
    container_name: forum-db
    restart: always
    environment:
      - MARIADB_DATABASE=forum
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=root
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root --password=root || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
