services:
  mysql:
    image: mysql:8.4.7
    container_name: forum-db
    restart: always
    environment:
      - MYSQL_DATABASE=forum
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s