services:
  mariadb:
    image: 'mariadb:latest'
    container_name: forum-db
    restart: always
    environment:
      - 'MARIADB_DATABASE=forum'
      - 'MARIADB_PASSWORD=root'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
    ports:
      - '3308:3306'
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 10s
      retries: 5
