services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=forum'
      - 'MARIADB_PASSWORD=root'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
    ports:
      - '3307:3306'
