spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
  application:
    name: ForumONE
  flyway:
    enabled: true
  security:
    user:
      name: user
      password: 1234568
      roles: USER
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: localhost
    port: 1025

api:
  base-url: http://localhost:8080
  front-url: http://localhost:4200

jwt:
  issuer: FORUM_ONE_JWT_ISSUER
  access-token:
    key: JWT_KEY_HASH
    expiration: 5 #expiration in minutes after creation
  refresh-token:
    key: ${jwt.access-token.key}
    expiration: 150