spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
  application:
    name: ForumONE
  flyway:
    enabled: true
  security:
    user:
      name: user
      password: 1234568
      roles: USER
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
