app:
  upload:
    base-dir: uploads/
    images:
      dir: images/
      max-size: 5MB
      allowed-types: image/jpeg,image/png

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: localhost
    port: 1025
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: forum

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  flyway:
    user: root
    password: root
    default-schema: forum
    driver-class-name: org.mariadb.jdbc.Driver
    create-schemas: true
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
  show-actuator: true

api:
  api-base: http://localhost:8080
  front-end: https://localhost:4200
  security:
    access-token:
      key: ${JWT_KEY_SECRET:7b4a52b6c723caf01718dcf7340396a9f9a0697c37deaef2a74ca419d47cb302}
      expiration: 15
    refresh-token:
      key: ${JWT_REFRESH_KEY_SECRET:7b4a52b6c723caf01718dcf7340396a9f9a0697c37deaef2a74ca419d47cb302}
      expiration: 10080

server:
  error:
    include-stacktrace: on_param

supabase:
  url: ${SUPABASE_URL:}
  key: ${SUPABASE_KEY:}
  bucket: ${SUPABASE_BUCKET:uploads}

