app:
  upload:
    base-dir: uploads/
    images:
      dir: images/
      max-size: 5MB
      allowed-types: image/jpeg,image/png

spring:
  mail:
    host: localhost
    port: 1025
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: forum

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  flyway:
    user: root
    password: root
    default-schema: forum
    driver-class-name: org.mariadb.jdbc.Driver
    create-schemas: true
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
  show-actuator: true

api:
  security:
    access-token:
      key: ${JWT_KEY_SECRET:my-secret-key}
      expiration: 15
    refresh-token:
      key: ${JWT_REFRESH_KEY_SECRET:my-refresh-key}
      expiration: 10080
